clc
addpath(genpath(strcat(pwd,'/LIB')))

fprintf('checking dependencies ...\n');

fprintf('(step 1/3): leave blank if mexopencv-master is inside LIB\n')
fprintf('else enter the path of mexopencv-master as /home/user/ ... /mexopencv-master  \n');

str = input('','s');

if ~isempty(str)
 addpath(genpath(str))
end

try
  cv.BackgroundSubtractorMOG();
  fprintf('[ok] mexopencv-master\n');
  clear;
catch
  fprintf('[error 1] mexopencv-master aborting ...\n');
  fprintf('(1) check if the path is correct.\n');
  fprintf('(2) check the warnings generated by mexopencv-master log installation.\n');
  fprintf('(3) check opencv 2.9.10 installation.\n');
  return
end

fprintf('(step 2/3): checking decoders ...\n');

ffmpeg_sppt = false;
avconv_sppt = false;

!ffmpeg -i ./DATA/Sample/crash0.mp4 -t 5 -vcodec rawvideo -pix_fmt yuv420p test0.avi
!ffmpeg -i ./DATA/Sample/crash0.mp4 -t 5 -vcodec rawvideo -pix_fmt rgb24 test1.avi
fprintf('\n\n');

try
  videoFReader = vision.VideoFileReader('test0.avi','ImageColorSpace','Intensity');
  step(videoFReader);
  ffmpeg_sppt = true;
catch
end
try
  videoFReader = vision.VideoFileReader('test1.avi','ImageColorSpace','Intensity');
  step(videoFReader);
  ffmpeg_sppt = true;
catch
end
!rm test0.avi
!rm test1.avi

!avconv -i ./DATA/Sample/crash0.mp4 -t 5 -vcodec rawvideo -pix_fmt yuv420p test0.avi
!avconv -i ./DATA/Sample/crash0.mp4 -t 5 -vcodec rawvideo -pix_fmt rgb24 test1.avi
fprintf('\n\n');

try
  videoFReader = vision.VideoFileReader('test0.avi','ImageColorSpace','Intensity');
  step(videoFReader);
  ffmpeg_sppt = true;
catch
end
try
  videoFReader = vision.VideoFileReader('test1.avi','ImageColorSpace','Intensity');
  step(videoFReader);
  ffmpeg_sppt = true;
catch
end
!rm test0.avi
!rm test1.avi

if avconv_sppt || ffmpeg_sppt
  fprintf('[ok] video decoder supported\n');
else
  fprintf('[error 2] video decoder not supported aborting\n');
  fprintf('(1) install required video decoder dependencies e.g. libav-tools or ffmpeg.\n');
  fprintf('(2) check the /usr/local/ folder for broken (.so) library links .\n ');
  return
end

fprintf('(step 3/3) creating mex HOF ...\n');

try
  cd LIB/
  mex mexhof.c
  cd ..
  fprintf('[ok] mex HOF\n');
catch
  fprintf('[error 3] please make sure gcc >= 4.4 g++ >= 4.4 is installed ...\n');
  return
end

clear

fprintf('All dependecies were met\n');

